"use client";

import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import ReactCountryFlag from "react-country-flag";
import { CircleNotch, DownloadSimple } from "@phosphor-icons/react";
import ScriptEditor from "../../dashboard/components/ScriptEditor";

interface ShareData {
  title: string;
  market_code: string;
  locale: string;
  content: string;
}

const COUNTRIES: Record<string, { label: string; countryCode: string }> = {
  IN: { label: "India", countryCode: "IN" },
  US: { label: "United States", countryCode: "US" },
  BR: { label: "Brazil", countryCode: "BR" },
  ID: { label: "Indonesia", countryCode: "ID" },
  MX: { label: "Mexico", countryCode: "MX" },
  VN: { label: "Vietnam", countryCode: "VN" },
  RU: { label: "Russia", countryCode: "RU" },
  TR: { label: "Turkey", countryCode: "TR" },
  JP: { label: "Japan", countryCode: "JP" },
  UK: { label: "United Kingdom", countryCode: "GB" },
  DE: { label: "Germany", countryCode: "DE" },
  KR: { label: "South Korea", countryCode: "KR" },
  FR: { label: "France", countryCode: "FR" },
  CA: { label: "Canada", countryCode: "CA" },
  AU: { label: "Australia", countryCode: "AU" },
};

export default function SharePage() {
  const { token } = useParams<{ token: string }>();
  const [data, setData] = useState<ShareData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [exporting, setExporting] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!token) return;
    fetch(`/api/share/${token}`)
      .then((res) => {
        if (!res.ok) throw new Error("Not found");
        return res.json();
      })
      .then((d: ShareData) => setData(d))
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, [token]);

  async function handleDownloadPdf() {
    if (!data || !contentRef.current) return;
    setExporting(true);

    try {
      const html2canvas = (await import("html2canvas-pro")).default;
      const { jsPDF } = await import("jspdf");

      const country = COUNTRIES[data.market_code];
      const dateStr = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });

      // Create an off-screen container with PDF-friendly styling
      const container = document.createElement("div");
      container.style.cssText =
        "position:absolute;left:-9999px;top:0;width:700px;background:#fff;padding:48px 48px 32px;font-family:system-ui,-apple-system,sans-serif;color:#18181b;";

      // Header
      const header = document.createElement("div");
      header.style.cssText =
        "display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;padding-bottom:20px;border-bottom:1px solid #e4e4e7;";
      header.innerHTML = `
        <div>
          <div style="font-size:11px;color:#a1a1aa;">${dateStr}</div>
          <div style="font-size:11px;color:#a1a1aa;margin-top:2px;">${country?.label || data.market_code}</div>
        </div>
      `;
      container.appendChild(header);

      // Title
      const title = document.createElement("h1");
      title.style.cssText =
        "font-size:22px;font-weight:600;color:#18181b;margin:0 0 24px;letter-spacing:-0.025em;";
      title.textContent = data.title;
      container.appendChild(title);

      // Script content — clone from the rendered editor
      const contentClone = contentRef.current.cloneNode(true) as HTMLElement;
      contentClone.style.cssText = "color:#3f3f46;";
      // Remove any dark mode classes from cloned content
      contentClone.querySelectorAll("[class]").forEach((el) => {
        const classes = Array.from(el.classList).filter((c) => !c.startsWith("dark:"));
        el.className = classes.join(" ");
      });
      container.appendChild(contentClone);

      // Footer
      const footer = document.createElement("div");
      footer.style.cssText =
        "margin-top:32px;padding-top:16px;border-top:1px solid #e4e4e7;font-size:10px;color:#a1a1aa;text-align:center;";
      footer.textContent = "Generated by ReelAtlas";
      container.appendChild(footer);

      document.body.appendChild(container);

      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
      });

      document.body.removeChild(container);

      const imgWidth = 210; // A4 width in mm
      const pageHeight = 297; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const pdf = new jsPDF("p", "mm", "a4");

      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(canvas.toDataURL("image/png"), "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft > 0) {
        position -= pageHeight;
        pdf.addPage();
        pdf.addImage(canvas.toDataURL("image/png"), "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      const safeTitle = data.title.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "-");
      pdf.save(`${safeTitle}-${data.market_code}.pdf`);
    } catch {
      // Fallback: open print dialog
      window.print();
    } finally {
      setExporting(false);
    }
  }

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center bg-white dark:bg-zinc-950">
        <CircleNotch size={24} className="animate-spin text-zinc-300 dark:text-zinc-700" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="flex h-screen flex-col items-center justify-center bg-white dark:bg-zinc-950">
        <p className="text-sm text-zinc-500">This share link is invalid or has been revoked.</p>
      </div>
    );
  }

  const country = COUNTRIES[data.market_code];

  return (
    <div className="flex h-screen flex-col bg-zinc-100 dark:bg-zinc-900">
      {/* Header */}
      <div className="flex shrink-0 items-center gap-3 border-b border-zinc-200 bg-white px-5 py-3 dark:border-zinc-800 dark:bg-zinc-950">
        <div className="min-w-0 flex-1">
          <h1 className="truncate text-sm font-medium text-zinc-900 dark:text-zinc-50">
            {data.title}
          </h1>
          <div className="flex items-center gap-1.5 mt-0.5">
            {country && (
              <ReactCountryFlag
                countryCode={country.countryCode}
                svg
                style={{ width: 12, height: 12 }}
                className="rounded-sm object-cover"
              />
            )}
            <p className="text-[10px] text-zinc-400 dark:text-zinc-600">
              {country?.label || data.market_code} • Read only
            </p>
          </div>
        </div>

        {/* Download PDF button */}
        <button
          onClick={handleDownloadPdf}
          disabled={exporting}
          className="flex items-center gap-1.5 rounded-md border border-zinc-200 px-2.5 py-1.5 text-[11px] font-medium text-zinc-600 transition-colors hover:bg-zinc-50 disabled:opacity-40 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800"
        >
          {exporting ? (
            <CircleNotch size={12} className="animate-spin" />
          ) : (
            <DownloadSimple size={12} />
          )}
          Download PDF
        </button>
      </div>

      {/* Content */}
      <div className="mx-3 mt-3 mb-3 flex flex-1 flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950">
        <div ref={contentRef} className="flex-1 overflow-y-auto">
          <ScriptEditor
            key={`share-${token}`}
            initialContent={data.content}
            editable={false}
          />
        </div>
      </div>
    </div>
  );
}
